export const REQUEST_GET_ALUDOC_SETTINGS = "REQUEST_GET_ALUDOC_SETTINGS";
export const RECEIVE_GET_ALUDOC_SETTINGS = "RECEIVE_GET_ALUDOC_SETTINGS";
export const REQUEST_ALUDOC_SETTINGS_ERROR = "REQUEST_ALUDOC_SETTINGS_ERROR";
export const REQUEST_SETTINGS_ERROR = "REQUEST_SETTINGS_ERROR";
export const REQUEST_SET_ALUDOC_SETTINGS = "REQUEST_SET_ALUDOC_SETTINGS";
export const RECEIVE_SET_ALUDOC_SETTINGS = "RECEIVE_SET_ALUDOC_SETTINGS";
export const REQUEST_GET_DAYS_UNTIL_EXPIRED = "REQUEST_GET_DAYS_UNTIL_EXPIRED";
export const RECEIVE_GET_DAYS_UNTIL_EXPIRED = "RECEIVE_GET_DAYS_UNTIL_EXPIRED";
export const REQUEST_CUSTOM_FIELDS = "REQUEST_CUSTOM_FIELDS";
export const RECEIVE_CUSTOM_FIELDS = "RECEIVE_CUSTOM_FIELDS";
export const REQUEST_CREATE_CUSTOM_FIELDS = "REQUEST_CREATE_CUSTOM_FIELDS";
export const RECEIVE_CREATE_CUSTOM_FIELDS = "RECEIVE_CREATE_CUSTOM_FIELDS";
export const REQUEST_EDIT_CUSTOM_FIELD_VISIBILITY =
  "REQUEST_EDIT_CUSTOM_FIELD_VISIBILITY";
export const RECEIVE_EDIT_CUSTOM_FIELD_VISIBILITY =
  "RECEIVE_EDIT_CUSTOM_FIELD_VISIBILITY";

export const REQUEST_CREATE_CUSTOM_FIELD_TYPE_LIST =
  "REQUEST_CREATE_CUSTOM_FIELD_TYPE_LIST";
export const RECEIVE_CREATE_CUSTOM_FIELD_TYPE_LIST =
  "RECEIVE_CREATE_CUSTOM_FIELD_TYPE_LIST";

export const REQUEST_CUSTOM_FIELD_TYPE_LIST_VALUES =
  "REQUEST_CUSTOM_FIELD_TYPE_LIST_VALUES";
export const RECEIVE_CUSTOM_FIELD_TYPE_LIST_VALUES =
  "RECEIVE_CUSTOM_FIELD_TYPE_LIST_VALUES";

export const REQUEST_CUSTOM_FIELDS_INTEGRATOR =
  "REQUEST_CUSTOM_FIELDS_INTEGRATOR";
export const RECEIVE_CUSTOM_FIELDS_INTEGRATOR =
  "RECEIVE_CUSTOM_FIELDS_INTEGRATOR";
export const REQUEST_DELETE_CUSTOM_FIELD = "REQUEST_DELETE_CUSTOM_FIELD";
export const RECEIVE_DELETE_CUSTOM_FIELD = "RECEIVE_DELETE_CUSTOM_FIELD";

export const REQUEST_DELETE_CUSTOM_FIELD_TYPE_LIST_VALUES =
  "REQUEST_DELETE_CUSTOM_FIELD_TYPE_LIST_VALUES";
export const RECEIVE_DELETE_CUSTOM_FIELD_TYPE_LIST_VALUES =
  "RECEIVE_DELETE_CUSTOM_FIELD_TYPE_LIST_VALUES";
export const REQUEST_NUMERICAL_RECORDS_SETTINGS =
  "REQUEST_NUMERICAL_RECORDS_SETTINGS";
export const RECEIVE_NUMERICAL_RECORDS_SETTINGS =
  "RECEIVE_NUMERICAL_RECORDS_SETTINGS";
export const REQUEST_SET_NUMERICAL_RECORDS_SETTINGS =
  "REQUEST_SET_NUMERICAL_RECORDS_SETTINGS";
export const RECEIVE_SET_NUMERICAL_RECORDS_SETTINGS =
  "RECEIVE_SET_NUMERICAL_RECORDS_SETTINGS";
export const REQUEST_GROUP_PERSON_SETTINGS = "REQUEST_GROUP_PERSON_SETTINGS";
export const RECEIVE_GROUP_PERSON_SETTINGS = "RECEIVE_GROUP_PERSON_SETTINGS";

export const UPDATE_CUSTOM_FIELD_STORE = "UPDATE_CUSTOM_FIELD_STORE";
export const REQUEST_GET_CUSTOM_FIELDS_MOBILE_VIBILITIES =
  "REQUEST_GET_CUSTOM_FIELDS_MOBILE_VIBILITIES";
export const RECEIVE_GET_CUSTOM_FIELDS_MOBILE_VIBILITIES =
  "RECEIVE_GET_CUSTOM_FIELDS_MOBILE_VIBILITIES";
export const REQUEST_UPDATE_CUSTOM_FIELDS_MOBILE_VIBILITIES =
  "REQUEST_UPDATE_CUSTOM_FIELDS_MOBILE_VIBILITIES";
export const RECEIVE_UPDATE_CUSTOM_FIELDS_MOBILE_VIBILITIES =
  "RECEIVE_UPDATE_CUSTOM_FIELDS_MOBILE_VIBILITIES";

export const SELECTED_PERSON_GROUP_CHANGE = "SELECTED_PERSON_GROUP_CHANGE";
export const REQUEST_SET_PERSON_GROUP_SETTINGS =
  "REQUEST_SET_PERSON_GROUP_SETTINGS";
export const RECEIVE_SET_PERSON_GROUP_SETTINGS =
  "RECEIVE_SET_PERSON_GROUP_SETTINGS";

export const selectedPersonGroupChange = (payload) => ({
  type: SELECTED_PERSON_GROUP_CHANGE,
  payload,
});

export const requestSetGroupPersonSetting = (payload) => ({
  type: REQUEST_SET_PERSON_GROUP_SETTINGS,
  payload,
});

export const requestGroupPersonSettings = (payload) => ({
  type: REQUEST_GROUP_PERSON_SETTINGS,
  payload,
});

export const requestCustomFields = () => ({
  type: REQUEST_CUSTOM_FIELDS,
});
export const requestGetCustomFieldsMobileVisibilities = () => ({
  type: REQUEST_GET_CUSTOM_FIELDS_MOBILE_VIBILITIES,
});
export const requestUpdateCustomFieldsMobileVisibilities = (data) => ({
  type: REQUEST_UPDATE_CUSTOM_FIELDS_MOBILE_VIBILITIES,
  data,
});

export const requestCreateCustomField = (customField) => ({
  type: REQUEST_CREATE_CUSTOM_FIELDS,
  customField,
});

export const updateCustomFieldStore = (customFields) => ({
  type: UPDATE_CUSTOM_FIELD_STORE,
  customFields,
});

export const requestEditCustomFieldVisibility = (customField) => ({
  type: REQUEST_EDIT_CUSTOM_FIELD_VISIBILITY,
  customField,
});

export const requestCustomFieldsTypeListValues = (customFieldId) => ({
  type: REQUEST_CUSTOM_FIELD_TYPE_LIST_VALUES,
  customFieldId,
});

export const requestCreateCustomFieldsTypeList = (customFieldValues) => ({
  type: REQUEST_CREATE_CUSTOM_FIELD_TYPE_LIST,
  customFieldValues,
});

export const requestCustomFieldsIntegrator = (data) => ({
  type: REQUEST_CUSTOM_FIELDS_INTEGRATOR,
  data,
});

export const requestDeleteField = (fieldId) => ({
  type: REQUEST_DELETE_CUSTOM_FIELD,
  fieldId,
});
export const requestDeleteCustomFieldListValues = (ids) => ({
  type: REQUEST_DELETE_CUSTOM_FIELD_TYPE_LIST_VALUES,
  ids,
});

export const requestDaysUntilExpired = () => ({
  type: REQUEST_GET_DAYS_UNTIL_EXPIRED,
});
export const requestNumericalRecordsSettings = () => ({
  type: REQUEST_NUMERICAL_RECORDS_SETTINGS,
});

export const requestSetNumericalRecordsSettings = (settings) => ({
  type: REQUEST_SET_NUMERICAL_RECORDS_SETTINGS,
  settings,
});

export const getAludocSettings = () => ({
  type: REQUEST_GET_ALUDOC_SETTINGS,
});

export const editAludocSettings = (settings) => ({
  type: REQUEST_SET_ALUDOC_SETTINGS,
  settings,
});
